### ISSUE TITLE
../src/compress/stream_compressor.cc:95:39: error: no matching member function for call to 'NewInstance'

### ISSUE THREAD

**Issue by patrickkh7788** [x25/node-zstd#3]
macOSX install report this error.

  CXX(target) Release/obj.target/compressor/src/compress/stream_compressor.o
../src/compress/stream_compressor.cc:95:39: error: no matching member function for call to 'NewInstance'
      info.GetReturnValue().Set(cons->NewInstance(argc, argv));
                                ~~~~~~^~~~~~~~~~~
/var/root/.node-gyp/10.6.0/include/node/v8.h:3914:44: note: candidate function not viable: requires single argument 'context', but 2 arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                           ^
/var/root/.node-gyp/10.6.0/include/node/v8.h:3911:44: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                           ^

**Comment by josephrocca** [comment]
Note to others landing here via Google, the `node-zstd` package acctually corresponds to this github repo:

https://github.com/zwb-ict/node-zstd/issues/1

@patrickkh7788 did you post here by accident? If so you should close this and re-open the one you closed over there :+1:
